server:
  port: 8787
dubbo:
  application:
    name: DubboClient
    metadata-type: remote
  config-center:
    address: nacos://localhost:9868
  registry:
    address: nacos://localhost:9868?registry-type=service
  protocol:
    name: dubbo
    port: 20886
  metadata-report:
    address: nacos://localhost:9868
    group: DEFAULT_GROUP
  consumer:
    check: false
